Added build step in build "main" and "pr" workflows
mozilla/firefox-translations pull request #117
Opened 2022-02-22 15:28 UTC by abhi-agg

- Helps in catching xpi build errors very early

2022-02-22 19:39 UTC, andrenatal approved these changes

2022-02-22 20:35 UTC, andrenatal requested changes
Let's try to upload the xpi instead a zip using v1 of the upload artifacts action. Like here https://github.com/mozilla/multi-account-containers/blob/main/.github/workflows/builds.yaml as mentioned here: https://github.com/mozilla/firefox-translations/pull/116#issuecomment-1048164063

@abhi-agg could you please try that?

2022-02-23 13:28 UTC, abhi-agg commented
@andrenatal I am on it

2022-02-24 10:55 UTC, abhi-agg commented
@andrenatal @eu9ene Could anyone of you please review this one?

2022-02-24 18:56 UTC, andrenatal approved these changes

2022-02-24 18:56 UTC, merged